### ISSUE TITLE
Fix Project.toml

### ISSUE THREAD

**Issue by ufechner7** [Cvikli/RelevanceStacktrace.jl#2]
Please change this line:
```
authors = ["Your Name <you@example.com>"]
```
In addition, reconsider the version number (should be 0.1 or 1.0) and perhaps add a compat entry for the Julia version...

**Comment by Cvikli** [comment]
What is the compat? Damn, I never checked the administration part!

Also thank you for noting! :D

**Comment by Cvikli** [comment]
OK, I got it! Pushing it now! :)
