### ISSUE TITLE
Unclear if 'bold' line is correctly marked on Windows

### ISSUE THREAD

**Issue by kafisatz** [Cvikli/RelevanceStacktrace.jl#3]
Hi. I only just installed this. When running into an error with DataFrames.append!, it seems to **bold** row in the DataFrames package, when the bold line should be mainscript.jl:23 which is the `append!` call below:

```append!(brawall,b,cols = :setequal,promote=false) ```

I am not sure if `KNOWN_MODULES_PATHS_2` needs to be adjusted for Windows...

<img width="1152" alt="error" src="https://user-images.githubusercontent.com/15026865/187435344-e983b93d-e454-4868-a405-84a697279632.png">

**Comment by kafisatz** [comment]
this is on Windows 10, Julia 1.8. Apologies for not providing an MWE, but you can see that it is a type issue when appending a DataFrame to another.

**Comment by kafisatz** [comment]
MWE 
```using Revise
using RelevanceStacktrace
df = DataFrame(x=[1,2],y=["a","mi"])
df2 = DataFrame(x=["1","2"],y=["a","mi"])
append!(df,df2)```

**Comment by Cvikli** [comment]
Hi!
You are right, that isn't correct! 
I will repair that! (But I will need you to test as I don't have windows atm ) 

Thank you for noting! 
Best!

**Comment by Cvikli** [comment]
Hey @kafisatz ! 
I made a commit. 
Are you able to test dev branch? Did this commit solve that issue once for all? :)

I just added your cases to the filter that could cover each cases in Windows too from now if everything is all right. :)

**Comment by kafisatz** [comment]
Dev branch says the last commit was on 21 August 2022 (well before I  reported this issue). Can you clarify please?

**Comment by Cvikli** [comment]
My fault sorry, something is odd here. 

No problem it is merged to master now. You can use the master too.

**Comment by Cvikli** [comment]
Can you check it @kafisatz is it any better on the main branch? :)

**Comment by kafisatz** [comment]
Hm. Now nothing is bold. As you can see I ran an include command.
<img width="811" alt="rst" src="https://user-images.githubusercontent.com/15026865/188626831-cca7865a-ea46-48f0-8ce3-333beb2f30e3.PNG">

**Comment by Cvikli** [comment]
Hi,
The `using RelevanceStacktrace` is after the error print. Actually the new stacktrace wasn't applied before the error. RelevanceStacktrace changes the stacktrace output style too, you can see it as it modify the 2 line print to 1 line.

**Comment by kafisatz** [comment]
Indeed things seem to work now.
First stacktrace is due to 'running each line' (CTRL + Enter), second one is from include command

<img width="1037" alt="pic" src="https://user-images.githubusercontent.com/15026865/189834892-7bbf659e-6a05-41c5-8f7c-7572060c9328.png">

**Comment by Cvikli** [comment]
Looks good!
Hope it works from now then! ;) 🤞
