### ISSUE TITLE
Improvment: Reverse the order of stacktrace, so the last line is the closes to the error and not the first

### ISSUE THREAD

**Issue by Sixzero** [Cvikli/RelevanceStacktrace.jl#4]
[Title]
So the last line would be the most important line and you don't have to scroll up to check stacktrace?

Python stacktrace works like this.

**Comment by Cvikli** [comment]
I checked and it needs a little bit more modification.

**Comment by Cvikli** [comment]
Great idea! I will do it next week maybe. :)
